/**
 * Rule-based account mapper — v2
 *
 * Maps known QBO/Xero/Excel account names to Easy Numbers input fields.
 * Now includes section-aware matching: if the parser tells us an account
 * is in the "income" section, that alone is enough to map it to revenue
 * with high confidence.
 *
 * Runs first on every import — no AI calls needed.
 * Returns matched fields + list of unmatched accounts for AI classification.
 */

const EASY_NUMBERS_FIELDS = [
  'revenue', 'cogs', 'owner_direct_labor', 'employee_direct_labor',
  'subcontractors', 'marketing', 'owner_management_wage', 'rent',
  'insurance', 'software_subscriptions', 'other_opex',
];

// Section → default field mapping (when name doesn't match but section is known)
const SECTION_DEFAULTS = {
  income: { field: 'revenue', confidence: 0.90 },
  cogs: { field: 'cogs', confidence: 0.85 },
  expenses: { field: 'other_opex', confidence: 0.70 },
};

// Normalized lookup: lowercase account name → Easy Numbers field
const ACCOUNT_MAP = {
  // ============ REVENUE ============
  'revenue': 'revenue',
  'sales': 'revenue',
  'income': 'revenue',
  'service revenue': 'revenue',
  'services revenue': 'revenue',
  'service income': 'revenue',
  'services income': 'revenue',
  'services': 'revenue',
  'product sales': 'revenue',
  'product revenue': 'revenue',
  'product income': 'revenue',
  'consulting income': 'revenue',
  'consulting revenue': 'revenue',
  'consulting fees': 'revenue',
  'professional fees earned': 'revenue',
  'fee income': 'revenue',
  'fees earned': 'revenue',
  'commission income': 'revenue',
  'commissions earned': 'revenue',
  'commissions': 'revenue',
  'contract revenue': 'revenue',
  'contract income': 'revenue',
  'project income': 'revenue',
  'project revenue': 'revenue',
  'job income': 'revenue',
  'job revenue': 'revenue',
  'maintenance income': 'revenue',
  'maintenance contracts': 'revenue',
  'maintenance revenue': 'revenue',
  'retainer income': 'revenue',
  'retainer revenue': 'revenue',
  'recurring revenue': 'revenue',
  'subscription income': 'revenue',
  'subscription revenue': 'revenue',
  'gross receipts': 'revenue',
  'gross sales': 'revenue',
  'gross revenue': 'revenue',
  'net sales': 'revenue',
  'net revenue': 'revenue',
  'billings': 'revenue',
  'collections': 'revenue',
  'receipts': 'revenue',
  'sales revenue': 'revenue',
  'sales income': 'revenue',
  'sales of product income': 'revenue',
  'sales of products': 'revenue',
  'operating revenue': 'revenue',
  'design income': 'revenue',
  'design revenue': 'revenue',
  'design services': 'revenue',
  'installation income': 'revenue',
  'installation revenue': 'revenue',
  'installation services': 'revenue',
  'repair income': 'revenue',
  'repair revenue': 'revenue',
  'repair services': 'revenue',
  'construction income': 'revenue',
  'construction revenue': 'revenue',
  'construction services': 'revenue',
  'cleaning income': 'revenue',
  'cleaning revenue': 'revenue',
  'cleaning services': 'revenue',
  'landscaping income': 'revenue',
  'landscaping revenue': 'revenue',
  'landscaping services': 'revenue',
  'lawn care': 'revenue',
  'lawn care services': 'revenue',
  'lawn maintenance': 'revenue',
  'hardscaping': 'revenue',
  'hardscaping services': 'revenue',
  'irrigation': 'revenue',
  'irrigation services': 'revenue',
  'tree services': 'revenue',
  'tree removal': 'revenue',
  'snow removal': 'revenue',
  'snow plowing': 'revenue',
  'plowing': 'revenue',
  'deck building': 'revenue',
  'deck services': 'revenue',
  'fence installation': 'revenue',
  'fencing': 'revenue',
  'patio': 'revenue',
  'patio services': 'revenue',
  'concrete': 'revenue',
  'concrete services': 'revenue',
  'painting': 'revenue',
  'painting services': 'revenue',
  'roofing': 'revenue',
  'roofing services': 'revenue',
  'plumbing': 'revenue',
  'plumbing services': 'revenue',
  'plumbing income': 'revenue',
  'electrical': 'revenue',
  'electrical services': 'revenue',
  'electrical income': 'revenue',
  'hvac': 'revenue',
  'hvac services': 'revenue',
  'hvac income': 'revenue',
  'heating': 'revenue',
  'cooling': 'revenue',
  'pest control services': 'revenue',
  'pressure washing': 'revenue',
  'power washing': 'revenue',
  'window cleaning': 'revenue',
  'remodeling': 'revenue',
  'remodeling services': 'revenue',
  'renovation': 'revenue',
  'renovation services': 'revenue',
  'management fees': 'revenue',
  'management fee income': 'revenue',
  'reimbursed expenses': 'revenue',
  'reimbursable expenses': 'other_opex',
  'reimbursements': 'revenue',
  'discounts given': 'revenue',
  'returns and allowances': 'revenue',
  'refunds': 'revenue',
  'shipping income': 'revenue',
  'freight income': 'revenue',
  'rental income': 'revenue',
  'interest income': 'revenue',
  'dividend income': 'revenue',
  'other income': 'revenue',
  'uncategorized income': 'revenue',
  'unapplied cash payment income': 'revenue',

  // ============ COGS ============
  'cost of goods sold': 'cogs',
  'cogs': 'cogs',
  'cost of sales': 'cogs',
  'cost of revenue': 'cogs',
  'cost of services': 'cogs',
  'cost of goods': 'cogs',
  'direct costs': 'cogs',
  'direct materials': 'cogs',
  'materials': 'cogs',
  'materials & supplies': 'cogs',
  'materials and supplies': 'cogs',
  'supplies': 'cogs',
  'job supplies': 'cogs',
  'job materials': 'cogs',
  'job materials cost': 'cogs',
  'project materials': 'cogs',
  'project supplies': 'cogs',
  'parts': 'cogs',
  'parts and materials': 'cogs',
  'equipment costs': 'cogs',
  'equipment rental': 'cogs',
  'equipment purchases': 'cogs',
  'tool purchases': 'cogs',
  'tools and equipment': 'cogs',
  'tools & small equipment': 'cogs',
  'small tools': 'cogs',
  'freight': 'cogs',
  'freight and shipping': 'cogs',
  'shipping': 'cogs',
  'shipping costs': 'cogs',
  'delivery': 'cogs',
  'delivery costs': 'cogs',
  'merchant fees': 'cogs',
  'credit card fees': 'cogs',
  'processing fees': 'cogs',
  'transaction fees': 'cogs',
  'mileage': 'cogs',
  'fuel': 'cogs',
  'gas': 'cogs',
  'permits and inspections': 'cogs',
  'building permits': 'cogs',
  'cost of labor': 'cogs',
  'plants': 'cogs',
  'plants and materials': 'cogs',
  'plant materials': 'cogs',
  'mulch': 'cogs',
  'stone': 'cogs',
  'gravel': 'cogs',
  'pavers': 'cogs',
  'lumber': 'cogs',
  'decking materials': 'cogs',
  'hardware': 'cogs',
  'fasteners': 'cogs',
  'seed and sod': 'cogs',
  'fertilizer': 'cogs',
  'chemicals': 'cogs',
  'soil': 'cogs',
  'topsoil': 'cogs',
  'sand': 'cogs',
  'aggregate': 'cogs',
  'dumpster': 'cogs',
  'disposal fees': 'cogs',
  'dump fees': 'cogs',

  // ============ OWNER PAY (management side — will be auto-split) ============
  'officer salary': 'owner_management_wage',
  'officer compensation': 'owner_management_wage',
  'officers compensation': 'owner_management_wage',
  "officer's compensation": 'owner_management_wage',
  'owner salary': 'owner_management_wage',
  'owner wages': 'owner_management_wage',
  'owner pay': 'owner_management_wage',
  'owner compensation': 'owner_management_wage',
  'owner draw': 'owner_management_wage',
  'owners draw': 'owner_management_wage',
  "owner's draw": 'owner_management_wage',
  'owner distribution': 'owner_management_wage',
  'owners salary': 'owner_management_wage',
  "owner's salary": 'owner_management_wage',
  "owner's compensation": 'owner_management_wage',
  'member draw': 'owner_management_wage',
  'member salary': 'owner_management_wage',
  'member distribution': 'owner_management_wage',
  'member compensation': 'owner_management_wage',
  'shareholder salary': 'owner_management_wage',
  'shareholder compensation': 'owner_management_wage',
  'guaranteed payment': 'owner_management_wage',
  'guaranteed payments': 'owner_management_wage',
  'guaranteed payments to partners': 'owner_management_wage',
  'management wage': 'owner_management_wage',
  'management salary': 'owner_management_wage',
  'executive compensation': 'owner_management_wage',
  'owner health insurance': 'owner_management_wage',

  // ============ EMPLOYEE DIRECT LABOR ============
  'payroll': 'employee_direct_labor',
  'payroll expense': 'employee_direct_labor',
  'payroll expenses': 'employee_direct_labor',
  'wages': 'employee_direct_labor',
  'salaries': 'employee_direct_labor',
  'salary expense': 'employee_direct_labor',
  'salaries and wages': 'employee_direct_labor',
  'wages and salaries': 'employee_direct_labor',
  'payroll & wages': 'employee_direct_labor',
  'payroll and wages': 'employee_direct_labor',
  'employee wages': 'employee_direct_labor',
  'employee salaries': 'employee_direct_labor',
  'direct labor': 'employee_direct_labor',
  'labor': 'employee_direct_labor',
  'labor costs': 'employee_direct_labor',
  'field labor': 'employee_direct_labor',
  'crew wages': 'employee_direct_labor',
  'crew labor': 'employee_direct_labor',
  'technician wages': 'employee_direct_labor',
  'production labor': 'employee_direct_labor',
  'cleaning staff': 'employee_direct_labor',
  'staff wages': 'employee_direct_labor',
  'gross wages': 'employee_direct_labor',
  'compensation': 'employee_direct_labor',
  'employee compensation': 'employee_direct_labor',
  'employee benefits': 'employee_direct_labor',
  'benefits': 'employee_direct_labor',
  'health insurance': 'employee_direct_labor',
  'health benefits': 'employee_direct_labor',
  'medical insurance': 'employee_direct_labor',
  'dental insurance': 'employee_direct_labor',
  'vision insurance': 'employee_direct_labor',
  'retirement': 'employee_direct_labor',
  'retirement plan': 'employee_direct_labor',
  '401k': 'employee_direct_labor',
  '401(k)': 'employee_direct_labor',
  '401k match': 'employee_direct_labor',
  'pension': 'employee_direct_labor',
  'simple ira': 'employee_direct_labor',
  'sep ira': 'employee_direct_labor',
  'payroll tax': 'employee_direct_labor',
  'payroll taxes': 'employee_direct_labor',
  'employer taxes': 'employee_direct_labor',
  'fica': 'employee_direct_labor',
  'fica expense': 'employee_direct_labor',
  'futa': 'employee_direct_labor',
  'suta': 'employee_direct_labor',
  'state unemployment': 'employee_direct_labor',
  'federal unemployment': 'employee_direct_labor',
  'workers comp': 'employee_direct_labor',
  'workers compensation': 'employee_direct_labor',
  "worker's compensation": 'employee_direct_labor',
  'workers comp insurance': 'employee_direct_labor',
  'payroll processing': 'employee_direct_labor',
  'payroll service': 'employee_direct_labor',
  'payroll processing fees': 'employee_direct_labor',
  'pto': 'employee_direct_labor',
  'paid time off': 'employee_direct_labor',
  'vacation pay': 'employee_direct_labor',
  'bonus': 'employee_direct_labor',
  'bonuses': 'employee_direct_labor',
  'commissions expense': 'employee_direct_labor',
  'commission expense': 'employee_direct_labor',

  // ============ SUBCONTRACTORS ============
  'contractors': 'subcontractors',
  'contractor': 'subcontractors',
  'subcontractor': 'subcontractors',
  'subcontractors': 'subcontractors',
  'sub contractor': 'subcontractors',
  'subcontractor expense': 'subcontractors',
  'subcontractor expenses': 'subcontractors',
  'subcontractors expense': 'subcontractors',
  'subs': 'subcontractors',
  'sub labor': 'subcontractors',
  'contract labor': 'subcontractors',
  '1099 labor': 'subcontractors',
  '1099 contractors': 'subcontractors',
  '1099': 'subcontractors',
  'outside services': 'subcontractors',
  'freelance': 'subcontractors',
  'freelancers': 'subcontractors',
  'contracted services': 'subcontractors',
  'independent contractor': 'subcontractors',
  'independent contractors': 'subcontractors',
  'temporary labor': 'subcontractors',
  'temp labor': 'subcontractors',
  'staffing': 'subcontractors',
  'staffing agency': 'subcontractors',
  'staffing expense': 'subcontractors',

  // ============ MARKETING ============
  'marketing': 'marketing',
  'marketing expense': 'marketing',
  'marketing expenses': 'marketing',
  'advertising': 'marketing',
  'advertising expense': 'marketing',
  'advertising expenses': 'marketing',
  'advertising & marketing': 'marketing',
  'advertising and marketing': 'marketing',
  'marketing & advertising': 'marketing',
  'ads': 'marketing',
  'digital marketing': 'marketing',
  'online advertising': 'marketing',
  'social media': 'marketing',
  'social media advertising': 'marketing',
  'social media marketing': 'marketing',
  'facebook ads': 'marketing',
  'google ads': 'marketing',
  'ppc': 'marketing',
  'seo': 'marketing',
  'search engine optimization': 'marketing',
  'promotion': 'marketing',
  'promotions': 'marketing',
  'promotional expense': 'marketing',
  'print advertising': 'marketing',
  'direct mail': 'marketing',
  'email marketing': 'marketing',
  'branding': 'marketing',
  'brand development': 'marketing',
  'trade show': 'marketing',
  'trade shows': 'marketing',
  'sponsorship': 'marketing',
  'sponsorships': 'marketing',
  'event marketing': 'marketing',
  'events': 'marketing',
  'signage': 'marketing',
  'business cards': 'marketing',
  'marketing agency': 'marketing',
  'agency fees': 'marketing',
  'video production': 'marketing',
  'photography': 'marketing',
  'public relations': 'marketing',
  'pr': 'marketing',
  'website': 'marketing',
  'website development': 'marketing',
  'website maintenance': 'marketing',
  'lead generation': 'marketing',
  'referral fees': 'marketing',
  'yard signs': 'marketing',
  'vehicle wrap': 'marketing',
  'vehicle wraps': 'marketing',
  'uniforms': 'marketing',
  'job signs': 'marketing',
  'lawn signs': 'marketing',

  // ============ RENT ============
  'rent': 'rent',
  'rent expense': 'rent',
  'office rent': 'rent',
  'warehouse rent': 'rent',
  'shop rent': 'rent',
  'building rent': 'rent',
  'lease': 'rent',
  'lease expense': 'rent',
  'building lease': 'rent',
  'facilities': 'rent',
  'facilities expense': 'rent',
  'occupancy': 'rent',
  'occupancy cost': 'rent',
  'occupancy costs': 'rent',
  'rent & facilities': 'rent',
  'rent and facilities': 'rent',
  'rent & lease': 'rent',
  'rent and lease': 'rent',
  'office space': 'rent',
  'storage': 'rent',
  'storage expense': 'rent',
  'storage rental': 'rent',
  'co-working': 'rent',
  'coworking': 'rent',
  'equipment lease': 'rent',
  'equipment leasing': 'rent',
  'vehicle lease': 'rent',
  'yard rent': 'rent',
  'shop lease': 'rent',

  // ============ INSURANCE ============
  'insurance': 'insurance',
  'insurance expense': 'insurance',
  'business insurance': 'insurance',
  'general insurance': 'insurance',
  'general liability': 'insurance',
  'general liability insurance': 'insurance',
  'liability insurance': 'insurance',
  'property insurance': 'insurance',
  'commercial insurance': 'insurance',
  'auto insurance': 'insurance',
  'vehicle insurance': 'insurance',
  'professional liability': 'insurance',
  'professional liability insurance': 'insurance',
  'e&o insurance': 'insurance',
  'errors and omissions': 'insurance',
  'umbrella insurance': 'insurance',
  'umbrella': 'insurance',
  'bonding': 'insurance',
  'surety bond': 'insurance',
  'surety bonds': 'insurance',
  'keyman insurance': 'insurance',
  'key man insurance': 'insurance',
  'business interruption insurance': 'insurance',
  'cyber insurance': 'insurance',

  // ============ SOFTWARE / SUBSCRIPTIONS ============
  'software': 'software_subscriptions',
  'software expense': 'software_subscriptions',
  'software & subscriptions': 'software_subscriptions',
  'software and subscriptions': 'software_subscriptions',
  'subscriptions': 'software_subscriptions',
  'subscription expense': 'software_subscriptions',
  'subscription expenses': 'software_subscriptions',
  'saas': 'software_subscriptions',
  'technology': 'software_subscriptions',
  'technology expense': 'software_subscriptions',
  'computer expense': 'software_subscriptions',
  'computer expenses': 'software_subscriptions',
  'computer & internet': 'software_subscriptions',
  'cloud services': 'software_subscriptions',
  'hosting': 'software_subscriptions',
  'web hosting': 'software_subscriptions',
  'it services': 'software_subscriptions',
  'it expense': 'software_subscriptions',
  'it expenses': 'software_subscriptions',
  'internet': 'software_subscriptions',
  'internet expense': 'software_subscriptions',
  'internet service': 'software_subscriptions',
  'domain': 'software_subscriptions',
  'domain expense': 'software_subscriptions',
  'quickbooks': 'software_subscriptions',
  'xero': 'software_subscriptions',
  'slack': 'software_subscriptions',
  'zoom': 'software_subscriptions',
  'microsoft 365': 'software_subscriptions',
  'google workspace': 'software_subscriptions',
  'crm': 'software_subscriptions',
  'crm software': 'software_subscriptions',
  'project management software': 'software_subscriptions',
  'accounting software': 'software_subscriptions',
  'app subscriptions': 'software_subscriptions',

  // ============ OTHER OPEX ============
  'office supplies': 'other_opex',
  'office supplies & software': 'other_opex',
  'office supplies and software': 'other_opex',
  'office expense': 'other_opex',
  'office expenses': 'other_opex',
  'utilities': 'other_opex',
  'utility expense': 'other_opex',
  'electric': 'other_opex',
  'electricity': 'other_opex',
  'gas (utility)': 'other_opex',
  'natural gas': 'other_opex',
  'water': 'other_opex',
  'water and sewer': 'other_opex',
  'telephone': 'other_opex',
  'telephone expense': 'other_opex',
  'phone': 'other_opex',
  'phone expense': 'other_opex',
  'cell phone': 'other_opex',
  'mobile phone': 'other_opex',
  'accounting': 'other_opex',
  'accounting fees': 'other_opex',
  'bookkeeping': 'other_opex',
  'legal': 'other_opex',
  'legal fees': 'other_opex',
  'legal expense': 'other_opex',
  'legal & professional services': 'other_opex',
  'legal and professional services': 'other_opex',
  'attorney fees': 'other_opex',
  'professional fees': 'other_opex',
  'professional services': 'other_opex',
  'consulting fees': 'other_opex',
  'coaching': 'other_opex',
  'education': 'other_opex',
  'training': 'other_opex',
  'training expense': 'other_opex',
  'continuing education': 'other_opex',
  'conferences': 'other_opex',
  'travel': 'other_opex',
  'travel expense': 'other_opex',
  'travel expenses': 'other_opex',
  'meals': 'other_opex',
  'meals & entertainment': 'other_opex',
  'meals and entertainment': 'other_opex',
  'entertainment': 'other_opex',
  'auto': 'other_opex',
  'auto expense': 'other_opex',
  'automobile expense': 'other_opex',
  'vehicle expense': 'other_opex',
  'vehicle expenses': 'other_opex',
  'car expense': 'other_opex',
  'gas and oil': 'other_opex',
  'gasoline': 'other_opex',
  'vehicle repairs': 'other_opex',
  'vehicle maintenance': 'other_opex',
  'car & truck': 'other_opex',
  'car and truck': 'other_opex',
  'truck expense': 'other_opex',
  'truck expenses': 'other_opex',
  'truck maintenance': 'other_opex',
  'truck repairs': 'other_opex',
  'fleet expense': 'other_opex',
  'parking': 'other_opex',
  'tolls': 'other_opex',
  'miscellaneous': 'other_opex',
  'miscellaneous expense': 'other_opex',
  'other expense': 'other_opex',
  'other expenses': 'other_opex',
  'other business expenses': 'other_opex',
  'other miscellaneous expense': 'other_opex',
  'general expense': 'other_opex',
  'general expenses': 'other_opex',
  'admin expense': 'other_opex',
  'administrative expense': 'other_opex',
  'general and administrative': 'other_opex',
  'g&a': 'other_opex',
  'bank fees': 'other_opex',
  'bank charges': 'other_opex',
  'bank charges & fees': 'other_opex',
  'bank charges and fees': 'other_opex',
  'bank service charges': 'other_opex',
  'service charges': 'other_opex',
  'interest expense': 'other_opex',
  'interest paid': 'other_opex',
  'loan interest': 'other_opex',
  'dues': 'other_opex',
  'dues & subscriptions': 'other_opex',
  'dues and subscriptions': 'other_opex',
  'memberships': 'other_opex',
  'membership dues': 'other_opex',
  'licenses': 'other_opex',
  'licenses & permits': 'other_opex',
  'licenses and permits': 'other_opex',
  'permits': 'other_opex',
  'business license': 'other_opex',
  'registration': 'other_opex',
  'taxes': 'other_opex',
  'taxes & licenses': 'other_opex',
  'taxes and licenses': 'other_opex',
  'business taxes': 'other_opex',
  'property tax': 'other_opex',
  'property taxes': 'other_opex',
  'sales tax expense': 'other_opex',
  'state tax': 'other_opex',
  'repairs': 'other_opex',
  'repairs & maintenance': 'other_opex',
  'repairs and maintenance': 'other_opex',
  'maintenance': 'other_opex',
  'maintenance expense': 'other_opex',
  'building maintenance': 'other_opex',
  'janitorial': 'other_opex',
  'cleaning': 'other_opex',
  'cleaning expense': 'other_opex',
  'depreciation': 'other_opex',
  'depreciation expense': 'other_opex',
  'amortization': 'other_opex',
  'amortization expense': 'other_opex',
  'bad debt': 'other_opex',
  'bad debt expense': 'other_opex',
  'write-offs': 'other_opex',
  'charitable contributions': 'other_opex',
  'donations': 'other_opex',
  'postage': 'other_opex',
  'postage & delivery': 'other_opex',
  'postage and delivery': 'other_opex',
  'shipping expense': 'other_opex',
  'printing': 'other_opex',
  'printing & reproduction': 'other_opex',
  'security': 'other_opex',
  'alarm service': 'other_opex',
  'pest control': 'other_opex',
  'trash removal': 'other_opex',
  'waste disposal': 'other_opex',
  'uniforms expense': 'other_opex',
  'uniform expense': 'other_opex',
  'laundry': 'other_opex',
  'penalties': 'other_opex',
  'fines': 'other_opex',
  'late fees': 'other_opex',
  'ask my accountant': 'other_opex',
  'uncategorized expense': 'other_opex',
  'reconciliation discrepancies': 'other_opex',
};

// Name-based matching: exact → cleaned → substring → partial
function matchByName(accountName) {
  const lower = accountName.toLowerCase().trim();

  if (ACCOUNT_MAP[lower]) {
    return { field: ACCOUNT_MAP[lower], confidence: 1.0, method: 'exact' };
  }

  // Strip common QBO prefixes/suffixes
  const cleaned = lower
    .replace(/^(total|net|gross)\s+/i, '')
    .replace(/\s*-\s*(other|general|primary)$/i, '')
    .replace(/\s*(expense|expenses|cost|costs|income|revenue)\s*$/i, '')
    .trim();

  if (cleaned && cleaned !== lower && ACCOUNT_MAP[cleaned]) {
    return { field: ACCOUNT_MAP[cleaned], confidence: 0.92, method: 'cleaned' };
  }

  // Substring: known key found inside the account name ("Job Materials Cost" contains "job materials")
  for (const [key, field] of Object.entries(ACCOUNT_MAP)) {
    if (key.length >= 4 && lower.includes(key)) {
      return { field, confidence: 0.85, method: 'substring' };
    }
  }

  // Reverse substring: account name found inside a known key
  for (const [key, field] of Object.entries(ACCOUNT_MAP)) {
    if (key.length >= 5 && lower.length >= 4 && key.includes(lower)) {
      return { field, confidence: 0.75, method: 'partial' };
    }
  }

  // Word overlap: if 2+ significant words match a key
  const words = lower.split(/\s+/).filter((w) => w.length >= 3);
  if (words.length >= 2) {
    for (const [key, field] of Object.entries(ACCOUNT_MAP)) {
      const keyWords = key.split(/\s+/);
      const overlap = words.filter((w) => keyWords.includes(w));
      if (overlap.length >= 2) {
        return { field, confidence: 0.80, method: 'word_overlap' };
      }
    }
  }

  return null;
}

/**
 * Maps an array of account line items to Easy Numbers fields.
 * Uses name matching first, then falls back to section-aware defaults.
 *
 * @param {Array<{name: string, amount: number, section?: string}>} accounts
 * @returns {{ matched: Array, unmatched: Array }}
 */
export function mapAccounts(accounts) {
  const matched = [];
  const unmatched = [];

  for (const account of accounts) {
    const nameResult = matchByName(account.name);

    if (nameResult) {
      matched.push({
        ...account,
        suggested_field: nameResult.field,
        confidence: nameResult.confidence,
        method: nameResult.method,
        source: 'rules',
      });
      continue;
    }

    // Section-aware fallback: if we know the P&L section, use it
    const sectionDefault = SECTION_DEFAULTS[account.section];
    if (sectionDefault) {
      matched.push({
        ...account,
        suggested_field: sectionDefault.field,
        confidence: sectionDefault.confidence,
        method: 'section_default',
        source: 'rules',
      });
      continue;
    }

    unmatched.push(account);
  }

  return { matched, unmatched };
}

export { EASY_NUMBERS_FIELDS, ACCOUNT_MAP };
